package manu.scrollwithsticky;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.LinearLayoutManager;
import android.view.View;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    private StickyRecyclerView recyclerview;
    private LinearLayoutManager linearLayoutManager;
    private StickyAdapter stickyAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        View titleView = findViewById(R.id.title);
        View subTitleView = findViewById(R.id.subtitle);

        recyclerview = (StickyRecyclerView) findViewById(R.id.recyclerview);
        linearLayoutManager = new LinearLayoutManager(this);
        recyclerview.setLayoutManager(linearLayoutManager);
        stickyAdapter = new StickyAdapter();
        recyclerview.setAdapter(stickyAdapter);
        recyclerview.setStickyTitle(titleView);
        recyclerview.setStickySubTitle(subTitleView);

        List<Cell> cellList = new ArrayList<Cell>();
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.EMPTY, ""));
        cellList.add(new Cell(Cell.CELL_TYPE.TITLE, "Titre 2"));
        cellList.add(new Cell(Cell.CELL_TYPE.SUBTITLE, "Sous-titre 1"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.SUBTITLE, "Sous-titre 2"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.EMPTY, ""));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.EMPTY, ""));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.TITLE, "Titre 3"));
        cellList.add(new Cell(Cell.CELL_TYPE.SUBTITLE, "Sous-titre 1"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.SUBTITLE, "Sous-titre 2"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.EMPTY, ""));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.TITLE, "Titre 4"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        cellList.add(new Cell(Cell.CELL_TYPE.NORMAL, "Normal"));
        stickyAdapter.setCellList(cellList);
    }
}
